### ISSUE TITLE
How to pass null as a param value?

### ISSUE THREAD

**Issue by HeyBanditoz** [jenetics/facilejdbc#47]
Let's say I have JDBC code that looks like this,
```java
try (Connection c = DATABASE.getConnection()) {
    PreparedStatement ps = c.prepareStatement("INSERT INTO table VALUES (?, ?)");
    if (isTrue()) {
        ps.setLong(1, 3000);
    }
	else {
		ps.setNull(1, Types.INTEGER);
	}
    // ...
}
```
For a FacileJDBC equivalent I was thinking of
```java
try (Conneciton c = DATABASE.getConnection()) {
	Query.of("INSERT INTO table VALUES (:a, :b)")
			.on(Param.value("a", (isTrue() ? 3000 : null)))
			.as(doTheThing(), c);
			// ...
}
```
The Param#value function doesn't accept nulls for its values, so I don't think this would work.
Is there an equivalent to the above JDBC code?

**Comment by jenetics** [comment]
You can use `Param.value("a", (isTrue() ? 3000 : Optional.empty()))`, but I think I should remove this null-check in a future version.

**Comment by jenetics** [comment]
Merged into r2.1.0.
